# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '4connect.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(636, 623)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(250, 60, 91, 23))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(60, 500, 47, 31))
        self.pushButton_3.setFont(font)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(130, 500, 47, 31))
        self.pushButton_4.setFont(font)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(200, 500, 47, 31))
        self.pushButton_5.setFont(font)
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(270, 500, 47, 31))
        self.pushButton_6.setFont(font)
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(340, 500, 47, 31))
        self.pushButton_7.setFont(font)
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(410, 500, 47, 31))
        self.pushButton_8.setFont(font)
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(480, 500, 47, 31))
        self.pushButton_9.setFont(font)
        self.L1 = QLabel(self.centralwidget)
        self.L1.setObjectName(u"L1")
        self.L1.setGeometry(QRect(60, 200, 47, 31))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setWeight(75)
        self.L1.setFont(font1)
        self.L1.setFrameShape(QFrame.WinPanel)
        self.L3 = QLabel(self.centralwidget)
        self.L3.setObjectName(u"L3")
        self.L3.setGeometry(QRect(60, 300, 47, 31))
        self.L3.setFont(font1)
        self.L3.setFrameShape(QFrame.WinPanel)
        self.L2 = QLabel(self.centralwidget)
        self.L2.setObjectName(u"L2")
        self.L2.setGeometry(QRect(60, 250, 47, 31))
        self.L2.setFont(font1)
        self.L2.setFrameShape(QFrame.WinPanel)
        self.L4 = QLabel(self.centralwidget)
        self.L4.setObjectName(u"L4")
        self.L4.setGeometry(QRect(60, 350, 47, 31))
        self.L4.setFont(font1)
        self.L4.setFrameShape(QFrame.WinPanel)
        self.L5 = QLabel(self.centralwidget)
        self.L5.setObjectName(u"L5")
        self.L5.setGeometry(QRect(60, 400, 47, 31))
        self.L5.setFont(font1)
        self.L5.setFrameShape(QFrame.WinPanel)
        self.L6 = QLabel(self.centralwidget)
        self.L6.setObjectName(u"L6")
        self.L6.setGeometry(QRect(60, 450, 47, 31))
        self.L6.setFont(font1)
        self.L6.setFrameShape(QFrame.WinPanel)
        self.L37 = QLabel(self.centralwidget)
        self.L37.setObjectName(u"L37")
        self.L37.setGeometry(QRect(481, 200, 47, 31))
        self.L37.setFont(font1)
        self.L37.setFrameShape(QFrame.WinPanel)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(130, 200, 47, 31))
        self.label_8.setFont(font1)
        self.label_8.setFrameShape(QFrame.WinPanel)
        self.L13 = QLabel(self.centralwidget)
        self.L13.setObjectName(u"L13")
        self.L13.setGeometry(QRect(200, 200, 47, 31))
        self.L13.setFont(font1)
        self.L13.setFrameShape(QFrame.WinPanel)
        self.L19 = QLabel(self.centralwidget)
        self.L19.setObjectName(u"L19")
        self.L19.setGeometry(QRect(270, 200, 47, 31))
        self.L19.setFont(font1)
        self.L19.setFrameShape(QFrame.WinPanel)
        self.L25 = QLabel(self.centralwidget)
        self.L25.setObjectName(u"L25")
        self.L25.setGeometry(QRect(340, 200, 47, 31))
        self.L25.setFont(font1)
        self.L25.setFrameShape(QFrame.WinPanel)
        self.L31 = QLabel(self.centralwidget)
        self.L31.setObjectName(u"L31")
        self.L31.setGeometry(QRect(410, 200, 47, 31))
        self.L31.setFont(font1)
        self.L31.setFrameShape(QFrame.WinPanel)
        self.L8 = QLabel(self.centralwidget)
        self.L8.setObjectName(u"L8")
        self.L8.setGeometry(QRect(130, 250, 47, 31))
        self.L8.setFont(font1)
        self.L8.setFrameShape(QFrame.WinPanel)
        self.L9 = QLabel(self.centralwidget)
        self.L9.setObjectName(u"L9")
        self.L9.setGeometry(QRect(130, 300, 47, 31))
        self.L9.setFont(font1)
        self.L9.setFrameShape(QFrame.WinPanel)
        self.L10 = QLabel(self.centralwidget)
        self.L10.setObjectName(u"L10")
        self.L10.setGeometry(QRect(130, 350, 47, 31))
        self.L10.setFont(font1)
        self.L10.setFrameShape(QFrame.WinPanel)
        self.L11 = QLabel(self.centralwidget)
        self.L11.setObjectName(u"L11")
        self.L11.setGeometry(QRect(130, 400, 47, 31))
        self.L11.setFont(font1)
        self.L11.setFrameShape(QFrame.WinPanel)
        self.L12 = QLabel(self.centralwidget)
        self.L12.setObjectName(u"L12")
        self.L12.setGeometry(QRect(130, 450, 47, 31))
        self.L12.setFont(font1)
        self.L12.setFrameShape(QFrame.WinPanel)
        self.L14 = QLabel(self.centralwidget)
        self.L14.setObjectName(u"L14")
        self.L14.setGeometry(QRect(200, 250, 47, 31))
        self.L14.setFont(font1)
        self.L14.setFrameShape(QFrame.WinPanel)
        self.L15 = QLabel(self.centralwidget)
        self.L15.setObjectName(u"L15")
        self.L15.setGeometry(QRect(200, 300, 47, 31))
        self.L15.setFont(font1)
        self.L15.setFrameShape(QFrame.WinPanel)
        self.L16 = QLabel(self.centralwidget)
        self.L16.setObjectName(u"L16")
        self.L16.setGeometry(QRect(200, 350, 47, 31))
        self.L16.setFont(font1)
        self.L16.setFrameShape(QFrame.WinPanel)
        self.L17 = QLabel(self.centralwidget)
        self.L17.setObjectName(u"L17")
        self.L17.setGeometry(QRect(200, 400, 47, 31))
        self.L17.setFont(font1)
        self.L17.setFrameShape(QFrame.WinPanel)
        self.L18 = QLabel(self.centralwidget)
        self.L18.setObjectName(u"L18")
        self.L18.setGeometry(QRect(200, 450, 47, 31))
        self.L18.setFont(font1)
        self.L18.setFrameShape(QFrame.WinPanel)
        self.L20 = QLabel(self.centralwidget)
        self.L20.setObjectName(u"L20")
        self.L20.setGeometry(QRect(270, 250, 47, 31))
        self.L20.setFont(font1)
        self.L20.setFrameShape(QFrame.WinPanel)
        self.L21 = QLabel(self.centralwidget)
        self.L21.setObjectName(u"L21")
        self.L21.setGeometry(QRect(270, 300, 47, 31))
        self.L21.setFont(font1)
        self.L21.setFrameShape(QFrame.WinPanel)
        self.L22 = QLabel(self.centralwidget)
        self.L22.setObjectName(u"L22")
        self.L22.setGeometry(QRect(270, 350, 47, 31))
        self.L22.setFont(font1)
        self.L22.setFrameShape(QFrame.WinPanel)
        self.L23 = QLabel(self.centralwidget)
        self.L23.setObjectName(u"L23")
        self.L23.setGeometry(QRect(270, 400, 47, 31))
        self.L23.setFont(font1)
        self.L23.setFrameShape(QFrame.WinPanel)
        self.L24 = QLabel(self.centralwidget)
        self.L24.setObjectName(u"L24")
        self.L24.setGeometry(QRect(270, 450, 47, 31))
        self.L24.setFont(font1)
        self.L24.setFrameShape(QFrame.WinPanel)
        self.L26 = QLabel(self.centralwidget)
        self.L26.setObjectName(u"L26")
        self.L26.setGeometry(QRect(340, 250, 47, 31))
        self.L26.setFont(font1)
        self.L26.setFrameShape(QFrame.WinPanel)
        self.L27 = QLabel(self.centralwidget)
        self.L27.setObjectName(u"L27")
        self.L27.setGeometry(QRect(340, 300, 47, 31))
        self.L27.setFont(font1)
        self.L27.setFrameShape(QFrame.WinPanel)
        self.L28 = QLabel(self.centralwidget)
        self.L28.setObjectName(u"L28")
        self.L28.setGeometry(QRect(340, 350, 47, 31))
        self.L28.setFont(font1)
        self.L28.setFrameShape(QFrame.WinPanel)
        self.L29 = QLabel(self.centralwidget)
        self.L29.setObjectName(u"L29")
        self.L29.setGeometry(QRect(340, 400, 47, 31))
        self.L29.setFont(font1)
        self.L29.setFrameShape(QFrame.WinPanel)
        self.L30 = QLabel(self.centralwidget)
        self.L30.setObjectName(u"L30")
        self.L30.setGeometry(QRect(340, 450, 47, 31))
        self.L30.setFont(font1)
        self.L30.setFrameShape(QFrame.WinPanel)
        self.L32 = QLabel(self.centralwidget)
        self.L32.setObjectName(u"L32")
        self.L32.setGeometry(QRect(410, 250, 47, 31))
        self.L32.setFont(font1)
        self.L32.setFrameShape(QFrame.WinPanel)
        self.L33 = QLabel(self.centralwidget)
        self.L33.setObjectName(u"L33")
        self.L33.setGeometry(QRect(410, 300, 47, 31))
        self.L33.setFont(font1)
        self.L33.setFrameShape(QFrame.WinPanel)
        self.L34 = QLabel(self.centralwidget)
        self.L34.setObjectName(u"L34")
        self.L34.setGeometry(QRect(410, 350, 47, 31))
        self.L34.setFont(font1)
        self.L34.setFrameShape(QFrame.WinPanel)
        self.L35 = QLabel(self.centralwidget)
        self.L35.setObjectName(u"L35")
        self.L35.setGeometry(QRect(410, 400, 47, 31))
        self.L35.setFont(font1)
        self.L35.setFrameShape(QFrame.WinPanel)
        self.L36 = QLabel(self.centralwidget)
        self.L36.setObjectName(u"L36")
        self.L36.setGeometry(QRect(410, 450, 47, 31))
        self.L36.setFont(font1)
        self.L36.setFrameShape(QFrame.WinPanel)
        self.L38 = QLabel(self.centralwidget)
        self.L38.setObjectName(u"L38")
        self.L38.setGeometry(QRect(480, 250, 47, 31))
        self.L38.setFont(font1)
        self.L38.setFrameShape(QFrame.WinPanel)
        self.L39 = QLabel(self.centralwidget)
        self.L39.setObjectName(u"L39")
        self.L39.setGeometry(QRect(480, 300, 47, 31))
        self.L39.setFont(font1)
        self.L39.setFrameShape(QFrame.WinPanel)
        self.L40 = QLabel(self.centralwidget)
        self.L40.setObjectName(u"L40")
        self.L40.setGeometry(QRect(480, 350, 47, 31))
        self.L40.setFont(font1)
        self.L40.setFrameShape(QFrame.WinPanel)
        self.L41 = QLabel(self.centralwidget)
        self.L41.setObjectName(u"L41")
        self.L41.setGeometry(QRect(480, 400, 47, 31))
        self.L41.setFont(font1)
        self.L41.setFrameShape(QFrame.WinPanel)
        self.L42 = QLabel(self.centralwidget)
        self.L42.setObjectName(u"L42")
        self.L42.setGeometry(QRect(480, 450, 47, 31))
        self.L42.setFont(font1)
        self.L42.setFrameShape(QFrame.WinPanel)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(60, 150, 111, 31))
        self.label_7.setFont(font)
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(60, 550, 471, 41))
        self.label_28.setFont(font)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(200, 100, 191, 29))
        self.horizontalLayout_5 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font)

        self.horizontalLayout_4.addWidget(self.label_5)

        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font1)

        self.horizontalLayout_4.addWidget(self.label_6)


        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)

        self.pushButton_2 = QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setFont(font)

        self.horizontalLayout_5.addWidget(self.pushButton_2)

        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(60, 20, 468, 29))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label = QLabel(self.layoutWidget1)
        self.label.setObjectName(u"label")
        self.label.setFont(font)

        self.horizontalLayout.addWidget(self.label)

        self.label_2 = QLabel(self.layoutWidget1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font1)

        self.horizontalLayout.addWidget(self.label_2)

        self.lineEdit = QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setFont(font)

        self.horizontalLayout.addWidget(self.lineEdit)


        self.horizontalLayout_3.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_3 = QLabel(self.layoutWidget1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font)

        self.horizontalLayout_2.addWidget(self.label_3)

        self.label_4 = QLabel(self.layoutWidget1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font1)

        self.horizontalLayout_2.addWidget(self.label_4)

        self.lineEdit_2 = QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setFont(font)

        self.horizontalLayout_2.addWidget(self.lineEdit_2)


        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Let's Toss", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Push", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Push", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Push", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Push", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Push", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Push", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Push", None))
        self.L1.setText("")
        self.L3.setText("")
        self.L2.setText("")
        self.L4.setText("")
        self.L5.setText("")
        self.L6.setText("")
        self.L37.setText("")
        self.label_8.setText("")
        self.L13.setText("")
        self.L19.setText("")
        self.L25.setText("")
        self.L31.setText("")
        self.L8.setText("")
        self.L9.setText("")
        self.L10.setText("")
        self.L11.setText("")
        self.L12.setText("")
        self.L14.setText("")
        self.L15.setText("")
        self.L16.setText("")
        self.L17.setText("")
        self.L18.setText("")
        self.L20.setText("")
        self.L21.setText("")
        self.L22.setText("")
        self.L23.setText("")
        self.L24.setText("")
        self.L26.setText("")
        self.L27.setText("")
        self.L28.setText("")
        self.L29.setText("")
        self.L30.setText("")
        self.L32.setText("")
        self.L33.setText("")
        self.L34.setText("")
        self.L35.setText("")
        self.L36.setText("")
        self.L38.setText("")
        self.L39.setText("")
        self.L40.setText("")
        self.L41.setText("")
        self.L42.setText("")
        self.label_7.setText("")
        self.label_28.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Winner", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.pushButton_2.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Player 1", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Player 2", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"=", None))
    # retranslateUi

